"""领域工具的声明式检索词汇；不读取或匹配用户消息，不承担Agent决策。"""

# 与ToolSpec的examples/related_tools共同构成检索元数据，Kernel只消费它们。

DOMAIN_ALIASES = {
    "guangya": "cloud",
    "downloads": "download",
    "local_media": "local_media",
    "media_proxy": "playback",
    "strm": "automation",
}

PREFIX_RETRIEVAL_TERMS: dict[str, tuple[str, ...]] = {
    "guangya": ("光鸭", "光鸭云盘", "云盘", "云端文件", "目录", "文件夹"),
    "provider": ("Jellyfin", "Emby", "qBittorrent", "qB", "媒体服务器", "实时"),
    "downloads": ("下载", "下载器", "qBittorrent", "qB", "任务", "进度"),
    "library": ("媒体库", "影片", "剧集", "集数", "入库"),
    "rss": ("RSS", "订阅源", "刷新周期", "排除关键字"),
    "media": ("媒体订阅", "追更", "订阅"),
    "indexer": ("资源", "资源搜索", "索引站", "种子", "磁力"),
    "discovery": ("推荐", "新剧", "电影", "剧集", "动漫", "国漫"),
    "web": ("联网", "网页", "链接", "公告", "文档", "最新", "定档", "公开信息"),
}

TOOL_RETRIEVAL_TERMS: dict[str, tuple[str, ...]] = {
    "recognition.inspect_filenames": (
        "真实文件名", "发布格式样本", "系统怎样识别", "文件名清洗", "清洗标题", "季和集",
        "季号", "集号", "中文英文标题", "发布组", "技术字段", "解析依据", "只读批量预览",
        "内置解析器", "不保存规则", "不要移动或改名", "目录上下文",
    ),
    "recognition.preview_release_format": (
        "发布格式教学", "识别错误", "识别错了", "集号识别错", "教你识别", "修订版", "字幕组格式", "先预览不要保存",
    ),
    "recognition.save_release_format": (
        "记住发布格式", "保存识别规则", "学会以后自动识别", "复用这个格式", "教学确认",
    ),
    "agent.capabilities": (
        "你是谁",
        "能做什么",
        "助手能力",
        "项目能力",
        "支持哪些功能",
    ),
    "local_media.retry_task": (
        "修正季集号",
        "纠正季集映射",
        "S02E12",
        "TMDB 集号超出",
        "集数识别错误",
        "指定第几季第几集",
        "连续集号改为季度集号",
    ),
    "guangya.fs.query": (
        "根目录",
        "列出目录",
        "目录内容",
        "查看目录",
        "浏览目录",
        "搜索文件",
        "查看文件夹",
        "子目录",
        "子目录名称",
        "文件夹名称",
        "目录下有哪些",
        "递归目录",
    ),
    "guangya.episode_naming.inspect": (
        "规整剧集命名",
        "修正剧集文件名",
        "按TMDB分季",
        "按 TMDB 集序",
        "发布组文件规整",
        "批量剧集改名",
        "创建Season目录",
        "方便整理入库",
        "长篇剧集目录",
    ),
    "guangya.episode_naming.plan": (
        "采用刚才的分季方案",
        "按已确认方案继续",
        "按TMDB标准分季",
        "生成分季确认卡",
        "一次改名",
        "不要拆批",
        "继续规整",
    ),
    "guangya.fs.change.preview": (
        "创建目录",
        "新建目录",
        "重命名",
        "改名",
        "移动",
        "复制",
        "拷贝",
        "备份到云盘目录",
        "回收站",
        "规整文件",
    ),
    "guangya.account.status": (
        "光鸭账号",
        "云盘容量",
        "剩余空间",
        "可用空间",
        "存储用量",
    ),
    "guangya.recycle.list": (
        "光鸭回收站",
        "回收站列表",
        "已删除文件",
        "垃圾箱内容",
    ),
    "guangya.recycle.restore": (
        "恢复回收站",
        "还原删除文件",
        "找回光鸭文件",
    ),
    "guangya.recycle.clear": (
        "清空回收站",
        "永久删除回收站",
        "彻底清理光鸭垃圾箱",
    ),
    "guangya.operation.status": (
        "光鸭任务状态",
        "恢复任务进度",
        "清空回收站进度",
    ),
    "guangya.share.list": (
        "光鸭分享列表",
        "我的分享",
        "已创建分享",
    ),
    "guangya.share.create": (
        "创建光鸭分享",
        "分享云盘文件",
        "生成分享链接",
        "提取码",
    ),
    "guangya.share.revoke": (
        "撤销光鸭分享",
        "取消分享链接",
        "删除分享",
    ),
    "provider.query": (
        "媒体总数",
        "媒体库统计",
        "媒体资源总量",
        "媒体库有多少资源",
        "媒体库有多少媒体",
        "电影剧集总数",
        "按媒体库统计",
        "指定媒体库数量",
        "动漫库有多少",
        "这个媒体库有多少部",
        "实时下载任务",
        "下载速度",
        "下载进度",
        "当前任务",
    ),
    "media.recommend_from_library": (
        "从媒体库推荐",
        "本地片单推荐",
        "今晚看什么",
        "今天心情很丧",
        "不用脑子",
        "爆笑",
        "无厘头",
        "日番",
        "推荐没看过的",
        "排除已看作品",
        "结合观看历史推荐",
        "Jellyfin 里值得看",
    ),
    "media.recently_played": (
        "最近播放",
        "播放历史",
        "观看历史",
        "最近看过",
        "我最近看了什么",
        "根据观看记录推荐",
        "根据最近播放推荐",
    ),
    "media.recently_added": (
        "最近入库",
        "最新入库",
        "最近添加",
        "媒体库最近新增",
    ),
    "media.continue_watching": (
        "继续观看",
        "没看完",
        "接着看",
        "Resume",
    ),
    "library.count_series_episodes": ("一共有多少集", "本地多少集", "季度分布"),
    "library.batch_presence": (
        "批量核对媒体库",
        "哪些在库",
        "缺哪几部",
        "缺少哪些电影",
        "片单收录情况",
        "导演作品在库情况",
    ),
    "indexer.search_resources": (
        "有没有资源",
        "搜索资源",
        "查找资源",
        "最近新出的步兵资源",
        "新出步兵",
        "无码资源",
        "uncensored",
        "Sukebei 最新",
        "成人资源索引",
    ),
    "ingest.submit": (
        "推送资源", "推送到云盘", "推送到光鸭", "按候选序号下载", "批量下载到云盘",
    ),
    "indexer.present_candidates": (
        "展示资源候选",
        "筛选资源候选",
        "选择候选资源",
        "展示第几个资源",
        "资源候选卡",
    ),
    "rss.subscription_summaries": (
        "配置了哪些RSS",
        "RSS订阅列表",
        "RSS订阅源",
        "我订阅了哪些RSS",
        "我订阅了那些RSS",
        "有哪些RSS",
        "RSS规则",
    ),
    "media.subscription_summaries": ("配置了哪些媒体订阅", "媒体追更列表"),
    "rss.create_subscription": ("添加RSS", "创建RSS订阅", "新增RSS订阅"),
    "discovery.anime_calendar": (
        "追漫日历",
        "动漫更新",
        "动画排期",
        "本周排期",
        "今日更新",
        "明天更新",
        "腾讯视频",
        "爱奇艺",
        "优酷",
        "国产动画排期",
    ),
    "discovery.recommend": (
        "最近推荐",
        "新剧推荐",
        "国漫推荐",
        "片单推荐",
        "根据观看记录推荐",
        "根据最近播放推荐",
    ),
    "discovery.person_filmography": (
        "导演的所有电影",
        "导演全部作品",
        "人物电影作品表",
        "演员参演电影",
        "编剧作品",
        "按上映年份排列",
        "诺兰电影",
    ),
    "web.search": (
        "2026新剧",
        "最新定档",
        "近期公开资讯",
        "近期步兵资源",
        "最近新出资源",
        "成人作品近期发行信息",
    ),
    "web.read": (
        "打开网页",
        "读取链接",
        "网页正文",
        "总结网页",
        "官方公告",
        "查看文档",
        "fetch url",
    ),
}
